services:
  app:
    build: .
    container_name: network-cli-assistant
    network_mode: "host"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    stdin_open: true
    tty: true
